#!/usr/bin/env ruby
# frozen_string_literal: true

repo_root = File.expand_path('..', File.dirname(File.realpath(__FILE__)))
$LOAD_PATH.unshift(File.join(repo_root, 'lib'))

require 'mitsubachi_infra/cli'

exit MitsubachiInfra::CLI.new(ARGV, repo_root: repo_root).run
